# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desocupado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('localidad', models.CharField(max_length=20, null=True)),
                ('estado_ocupacion', models.BooleanField(default=False)),
                ('experiencia_laboral', models.TextField(null=True)),
                ('formacion', models.TextField(null=True)),
                ('habilidades', models.TextField(null=True)),
                ('trabajo_realizable', models.CharField(max_length=50, null=True)),
                ('dni', models.CharField(max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.IntegerField(default=0)),
                ('razon_social', models.CharField(max_length=50, null=True)),
                ('rubro', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_trabajo', models.CharField(max_length=50)),
            ],
        ),
    ]
