# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app.core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioContrato', models.DateField()),
                ('finContrato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField()),
                ('inicioContrato', models.DateField()),
                ('finContrato', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeTrabajo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='OfertaLaboral',
        ),
    ]
